# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 772afb28d177064e7d02583cb1124db7e95cd66657e52b902a71a97a5982adb88eddb9d786fc989929f9a77d9a9ab44b87c3d3fd4c6939422d2e71e88bcd7abe

test:
  secret_key_base: 7582f4426fdc64def0882029293d942f728e870c5ffea17e203e957a685574665d94d8d17ac2d30ee5305a41485fce731f71173173454fc4350eab95ad68c28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
